version: '3'
services:
    web:
        build:
            dockerfile: src/Dockerfile
            context: .
            target: publish
        ports:
            - "5001:5001"
            - "44349:44349"
        depends_on:
            - mssql
    mssql:
        build:
            dockerfile: db/Dockerfile
            context: .
        ports:
            - "1433:1433"
    base:
        build:
            dockerfile: src/Dockerfile
            context: .
            target: build
        ports:
            - "5001:5001"
            - "44349:44349"
        profiles:
            - base
    migration:
        build:
            dockerfile: src/Dockerfile
            context: .
            target: migration
        depends_on:
            - mssql
        profiles:
            - migration